// <auto-generated />
namespace Qly_Nhan_Vien_Luong_Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AllowFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllowFK));
        
        string IMigrationMetadata.Id
        {
            get { return "201610160523588_AllowFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
