// <auto-generated />
namespace Qly_Luong_NVien_Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditTableHangSo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTableHangSo));
        
        string IMigrationMetadata.Id
        {
            get { return "201611220550463_EditTableHangSo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
